version: "3.7"
services:
    article_counter:
        build: .
        image: asset_trends
        command: run count_articles
        environment:
            - NEWS_API_TOKEN

    price_checker:
        image: asset_trends
        command: run check_prices

    prometheus:
        image: prom/prometheus
        ports:
            - "9090:9090"
        volumes:
            - type: bind
              source: ./conf/prometheus.yml
              target: /etc/prometheus/prometheus.yml
              read_only: true
            - type: volume
              source: prometheus_data
              target: /prometheus
        privileged: false   # Set to True if the container logs a "panic: syscall.Getrlimit failed: operation not permitted" error
        command:
        - "--config.file=/etc/prometheus/prometheus.yml"
        - "--storage.tsdb.path=/prometheus"
        - "--storage.tsdb.retention.time=90d"
        - "--web.console.libraries=/usr/share/prometheus/console_libraries"
        - "--web.console.templates=/usr/share/prometheus/consoles"

    grafana:
        image: grafana/grafana
        ports:
            - "3000:3000"
        volumes:
            - type: bind
              source: ./conf/grafana.db
              target: /var/lib/grafana/grafana.db

volumes:
    prometheus_data:
