version: "3.7"
services:
    article_counter:
        build: .
        image: asset_trends
        command: src/count_articles.py
        environment:
            - NEWS_API_TOKEN

    price_checker:
        image: asset_trends
        command: src/check_prices.py

    prometheus:
        image: prom/prometheus
        ports:
            - "9090:9090"
        volumes:
            - type: volume
              source: prometheus_data
              target: /opt
        privileged: false   # Set to True if the container logs a "panic: syscall.Getrlimit failed: operation not permitted" error
        command:
        - "--config.file=/opt/prometheus/prometheus.yml"
        - "--storage.tsdb.path=/opt/prometheus/data"
        - "--storage.tsdb.retention.time=90d"
        - "--web.console.libraries=/usr/share/prometheus/console_libraries"
        - "--web.console.templates=/usr/share/prometheus/consoles"

    grafana:
        image: grafana/grafana
        ports:
            - "3000:3000"
        volumes:
            - type: volume
              source: grafana_data
              target: /opt
        environment:
            - GF_PATHS_DATA=/opt/grafana

volumes:
    prometheus_data:
        external: true
    grafana_data:
        external: true
